### ISSUE TITLE
Alternative Approach for Extracting Elevation Data

### ISSUE THREAD

**Issue by cheginit** [ACWI-SSWD/nldi-xstool#5]
I have a couple of suggestions:

1. Using `py3dep.elevation_bycoords` for getting elevation data that uses [Bulk Elevation Point Query Service](https://apps.nationalmap.gov/bulkpqs/) from the National Map.
2. Using `shapely` for computing distance and interpolation along flow lines.
3. Using `scipy` for computing cross-section lines that are perpendicular to flow lines.
4. Using `distance` in addition to (or instead of) number of points for extracting elevation.

I added a new [notebook](https://hyriver.readthedocs.io/en/latest/notebooks/cross_section.html) to HyRiver's example gallery that demonstrates these suggestions.

Edit: Updated the notebook link.

**Comment by rmcd-mscb** [comment]
Thank you @cheginit.  I'll take a look.  Very much appreciate you taking the time to think about it.

**Comment by cheginit** [comment]
Sure. Please let me know if you have any questions.

**Comment by cheginit** [comment]
I just pushed some changes to the notebook. I added getting elevation using `getmap` function and added a filling depressions step that can help fix some of the issues with the DEM. You can check it out [here](https://github.com/cheginit/HyRiver-examples/blob/main/notebooks/cross_section.ipynb).

**Comment by rmcd-mscb** [comment]
Thanks @cheginit.  I've looked through your notebook a couple times and have some thoughts.  Would you have some time to get together on a call to talk about these ideas?

**Comment by cheginit** [comment]
Sure, would be happy to.
